forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^problems/(?P<problem_id>[0-9]*)$', views.thread, name='thread'),
    url(r'^solutions/(?P<solution_id>[0-9]+)/edit/(?P<rev_val>[0-9]*)$', views.edit_solution, name='edit_solution'),
    url(r'^problems/post$', views.post_problem, name='post_problem'),
    url(r'^problems/(?P<problem_id>[0-9]+)/edit/(?P<rev_val>[0-9]*)$', views.edit_problem, name='edit_problem'),
    url(r'^search-goal/$', views.search_goal, name='search_goal'),
    url(r'^goals/post$', views.post_goal, name='post_goal'),
    url(r'^goals/(?P<goal_id>[0-9]+)/edit/(?P<rev_val>[0-9]*)$', views.edit_goal, name='edit_goal'),
    url(r'^goals/(?P<goal_id>[0-9]+)$', views.goal, name='goal'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^qs/(?P<post_id>[0-9]+)/(?P<post_type>[0-9]+)$', views.question, name='question'),
]

global/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^', include('forum.urls', namespace="forum")),
]

forum/models/base.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    author = models.ForeignKey(User, related_name="%(app_label)s_created_%(class)ss")
    voted_users = models.ManyToManyField(User, related_name="%(app_label)s_liked_%(class)ss")
    points = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)

    class Meta:
        abstract = True
        app_label = 'forum'

global/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}


<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon staff -->
    <link rel="shortcut icon" type="image/png" href={% static "images/favicon/favicon.ico" %}/>
    <!-- favicon staff -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed&amp;subset=latin,greek,cyrillic,greek-ext,vietnamese,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
    <script src={% static "js/jquery-1.12.0.js" %}></script>
    <script src={% static "js/bootstrap.min.js" %}></script>
    <script src={% static "js/script.js" %}></script>

    <link rel="stylesheet" href={% static "css/styles.css" %}>
    <title>Open Problems</title>
    <meta name="keywords" content="problem solving, global problems, unsolved problems, existing problems, open problems">
    <meta name="description" content="Global Problem Solving Forum">

</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'forum:index' %}">Brand</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <form class="navbar-form navbar-right" role="search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search Problems&amp;Goals">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Go!</button>
                  </span>
                </div><!-- /input-group -->
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Problems</a></li>
                <li><a href="{% url 'forum:post_problem' %}">Post Problem</a></li>
                <li><a href="#">Goals</a></li>
                <li><a href="{% url 'forum:post_goal' %}">Post Goal</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'forum:profile' %}">{{ user.username}}</a></li>
                {% else %}
                    <li><a href="#">Signup</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div> <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<div class="container-fluid content-container">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>