forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^problems/(?P<problem_id>[0-9]*)$', views.thread, name='thread'),
    url(r'^solutions/(?P<solution_id>[0-9]+)/edit/(?P<rev_val>[0-9]*)$', views.edit_solution, name='edit_solution'),
    url(r'^problems/post$', views.post_problem, name='post_problem'),
    url(r'^problems/(?P<problem_id>[0-9]+)/edit/(?P<rev_val>[0-9]*)$', views.edit_problem, name='edit_problem'),
    url(r'^search-goal/$', views.search_goal, name='search_goal'),
    url(r'^goals/post$', views.post_goal, name='post_goal'),
    url(r'^goals/(?P<goal_id>[0-9]+)/edit/(?P<rev_val>[0-9]*)$', views.edit_goal, name='edit_goal'),
    url(r'^goals/(?P<goal_id>[0-9]+)$', views.goal, name='goal'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^qs/(?P<post_id>[0-9]+)/(?P<post_type>[0-9]+)$', views.question, name='question'),
]

global/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^', include('forum.urls', namespace="forum")),
]

forum/models/area.py
from django.db import models
from django.contrib.auth.models import User
from forum.models import Goal, Problem

class Area(models.Model):
    """Popularly known as tags"""

    name = models.CharField(max_length=254)
    author = models.ForeignKey(User, related_name='created_areas')

    problem = models.ManyToManyField(Problem, related_name='areas')
    goal = models.ManyToManyField(Goal, related_name='areas')

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'forum'

forum/models/base.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    author = models.ForeignKey(User, related_name="%(app_label)s_created_%(class)ss")
    voted_users = models.ManyToManyField(User, related_name="%(app_label)s_liked_%(class)ss")
    points = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)

    class Meta:
        abstract = True
        app_label = 'forum'

forum/models/goal.py
from django.db import models
from forum.models.base import Post

class GoalGeneric(models.Model):
    title = models.CharField(max_length=254)
    description = models.TextField()

    targets = models.TextField(blank=True)
    achievements = models.TextField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True

class Goal(Post, GoalGeneric):
    pass

class GoalRevision(Post, GoalGeneric):
    goal = models.ForeignKey(Goal, related_name="revisions")

forum/models/problem.py
from django.db import models
from forum.models.base import Post
from forum.models import Goal

class ProblemGeneric(models.Model):
    title = models.CharField(max_length=254)
    description = models.TextField()
    source = models.TextField(blank=True)
    curr_solution = models.TextField(blank=True)
    lim_curr_solution = models.TextField(blank=True)
    attempts = models.TextField(blank=True)
    specific_goal = models.TextField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True

class Problem(Post, ProblemGeneric):
    goal = models.ForeignKey(Goal, null=True, blank=True, related_name='problems')

class ProblemRevision(Post, ProblemGeneric):
    problem = models.ForeignKey(Problem, related_name="revisions")

forum/models/question.py
from django.db import models
from forum.models.base import Post
from forum.models import Problem, Solution, Goal

class Question(Post):
    body = models.TextField()

    def __str__(self):
        return self.body

class ProblemQuestion(Question):
    post = models.ForeignKey(Problem, related_name='questions')

class SolutionQuestion(Question):
    post = models.ForeignKey(Solution, related_name='questions')

class GoalQuestion(Question):
    post = models.ForeignKey(Goal, related_name='questions')

forum/models/solution.py
from django.db import models
from forum.models.base import Post
from forum.models import Problem


class SolutionGeneric(models.Model):

    body = models.TextField()

    class Meta:
        abstract = True

    def __str__(self):
        return self.body

class Solution(Post, SolutionGeneric):
    problem = models.ForeignKey(Problem, related_name='solutions')

class SolutionRevision(Post, SolutionGeneric):
    solution = models.ForeignKey(Solution, related_name="revisions")

forum/forms/goal.py
from django.forms import ModelForm, ModelChoiceField
from forum.models import Goal

class GoalForm(ModelForm):

    class Meta:
        model = Goal
        fields = ['title', 'description', 'targets', 'achievements']


class EditGoalForm(GoalForm):

    revisions = ModelChoiceField(queryset=None, empty_label=None)

    def __init__(self, *args, **kwargs):
        self.goal = kwargs.pop('goal')
        super(GoalForm, self).__init__(*args, **kwargs)
        self.fields['revisions'].queryset = self.goal.revisions.all()

forum/forms/problem.py
from django.forms import ModelForm, ModelChoiceField
from forum.models import Problem

class ProblemForm(ModelForm):

    class Meta:
        model = Problem
        fields = ['goal', 'title', 'description', 'source', 'curr_solution', 'lim_curr_solution', 'attempts', 'specific_goal']

class EditProblemForm(ProblemForm):

    revisions = ModelChoiceField(queryset=None, empty_label=None)

    def __init__(self, *args, **kwargs):
        self.problem = kwargs.pop('problem')
        super(ProblemForm, self).__init__(*args, **kwargs)
        self.fields['revisions'].queryset = self.problem.revisions.all()

forum/forms/question.py
from django.forms import ModelForm, Textarea
from forum.models import ProblemQuestion, SolutionQuestion, GoalQuestion

class ProblemQuestionForm(ModelForm):

    class Meta:
        model = ProblemQuestion
        fields = ['body']
        widgets = {
            'body': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

class SolutionQuestionForm(ModelForm):

    class Meta:
        model = SolutionQuestion
        fields = ['body']
        widgets = {
            'body': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

class GoalQuestionForm(ModelForm):

    class Meta:
        model = GoalQuestion
        fields = ['body']
        widgets = {
            'body': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

forum/forms/solution.py
from django.forms import ModelForm, ModelChoiceField
from forum.models import Solution

class SolutionForm(ModelForm):

    class Meta:
        model = Solution
        fields = ['body']

class EditSolutionForm(SolutionForm):

    revisions = ModelChoiceField(queryset=None, empty_label=None)

    def __init__(self, *args, **kwargs):
        self.solution = kwargs.pop('solution')
        super(SolutionForm, self).__init__(*args, **kwargs)
        self.fields['revisions'].queryset = self.solution.revisions.all()

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from forum.models import Problem, ProblemRevision, Goal, GoalRevision, Solution,\
                        SolutionRevision
from forum.forms import ProblemForm, EditProblemForm, GoalForm, EditGoalForm,\
                        SolutionForm, EditSolutionForm, ProblemQuestionForm,\
                        SolutionQuestionForm, GoalQuestionForm


def index(request):

    problems = Problem.objects.all()

    return render(request, 'index.html', {'problems': problems
                                        })



def populate_goal(revision, goal):
    data = {'title': revision.title, 'description': revision.description, 'targets': revision.targets,
                'achievements': revision.achievements}
    form = EditGoalForm(goal=goal, initial=data)
    return form

def populate_problem(revision, problem):
    data = {'title': revision.title, 'description': revision.description,
                            'source': revision.source, 'curr_solution': revision.curr_solution,
                            'lim_curr_solution': revision.lim_curr_solution, 'attempts': revision.attempts,
                            'specific_goal': revision.specific_goal}
    form = EditProblemForm(problem=problem, initial=data)
    return form

def populate_solution(revision, solution):
    data = {'body': revision.body}
    form = EditSolutionForm(solution=solution, initial=data)
    return form

def populate_form(rev_val, post):
    if rev_val:
        if post.__class__ == Solution:
            revision = get_object_or_404(SolutionRevision, pk=rev_val)
            form = populate_solution(revision, post)
            return form
        elif post.__class__ == Problem:
            revision = get_object_or_404(ProblemRevision, pk=rev_val)
            form = populate_problem(revision, post)
            return form
        else:
            revision = get_object_or_404(GoalRevision, pk=rev_val)
            form = populate_goal(revision, post)
            return form
    else:
        #if no rev_val present in GET request, pick the latest revision as default
        revision = post.revisions.all()[0]
        if post.__class__ == Solution:
            form = populate_solution(revision, post)
            return form
        elif post.__class__ == Problem:
            form = populate_problem(revision, post)
            return form
        else:
            form = populate_goal(revision, post)
            return form


def thread(request, problem_id):

    problem = get_object_or_404(Problem, pk=problem_id)

    if request.method == 'POST':
        form = SolutionForm(request.POST)
        if form.is_valid():
            solution = form.save(commit=False)
            init_rev = SolutionRevision(body=solution.body, author=request.user)
            return handle_form(solution, init_rev, request, problem)[0]
    else:
        form = SolutionForm()



    solutions = problem.solutions.order_by('points')

    related_problems = problem.goal.problems.exclude(pk=problem_id)

    problem_questions = problem.questions.all()

    pq_form = ProblemQuestionForm()

    sq_form = SolutionQuestionForm()

    return render(request, 'problems/thread.html', {'solutions': solutions,
                                                    'problem': problem,
                                                    'related_problems': related_problems,
                                                    'body': form['body'],
                                                    'problem_questions': problem_questions,
                                                    'pq_body': pq_form['body'],
                                                    'sq_body': sq_form['body'],
                                                    })



@login_required
def edit_solution(request, solution_id, rev_val):

    solution = get_object_or_404(Solution, pk=solution_id)

    if request.method == 'POST':
        form = SolutionForm(request.POST)
        if form.is_valid():
            rev = form.save(commit=False)
            rev = SolutionRevision(body=rev.body, author=request.user)
            return handle_form(solution, rev)[0]
    else:
        form = populate_form(rev_val, solution)

    return render(request, 'solutions/edit.html',{'revisions': form['revisions'],
                                                  'body': form['body'],
                                                  'solution_id': solution_id,
                                            })

def handle_form(post, rev, request=None, problem=None):

    name = post.__class__.__name__.lower()

    if request:
        post.author = request.user

    if problem:
        problem.solutions.add(post)

    post.save()
    post.revisions.add(rev)
    if name == 'solution':
        post.body = rev.body
    elif name == 'problem':
        post.title, post.description, post.source, post.curr_solution, post.lim_curr_solution,\
        post.attempts, post.specific_goal = rev.title, rev.description, rev.source, \
        rev.curr_solution, rev.lim_curr_solution, rev.attempts, rev.specific_goal
    else:
        post.title, post.description, post.targets, post.achievements = rev.title, \
        rev.description, rev.targets, rev.achievements

    post.save()


    return (HttpResponseRedirect(reverse('forum:{0}'.format(name if name == 'goal' else 'thread'),
                                 args=(post.id if name != 'solution' else post.problem.id,))),)

@login_required
def post_problem(request):

    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            init_rev = ProblemRevision(title=problem.title, description=problem.description,
                            source=problem.source, curr_solution=problem.curr_solution,
                            lim_curr_solution=problem.lim_curr_solution, attempts=problem.attempts,
                            specific_goal=problem.specific_goal, author=request.user)
            return handle_form(problem, init_rev, request)[0]
    else:
        form = ProblemForm()

    return render(request, 'problems/post.html',{'goal': form['goal'],
                                                'title': form['title'],
                                                'description': form['description'],
                                                'source': form['source'],
                                                'curr_solution': form['curr_solution'],
                                                'lim_curr_solution': form['lim_curr_solution'],
                                                'attempts': form['attempts'],
                                                'specific_goal': form['specific_goal'],
                                                })


@login_required
def edit_problem(request, problem_id, rev_val):

    problem = get_object_or_404(Problem, pk=problem_id)

    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            rev = form.save(commit=False)
            rev = ProblemRevision(title=rev.title, description=rev.description,
                            source=rev.source, curr_solution=rev.curr_solution,
                            lim_curr_solution=rev.lim_curr_solution, attempts=rev.attempts,
                            specific_goal=rev.specific_goal, author=request.user)
            return handle_form(problem, rev)[0]
    else:
        form = populate_form(rev_val, problem)

    return render(request, 'problems/edit.html',{'revisions': form['revisions'],
                                                'goal': form['goal'],
                                                'title': form['title'],
                                                'description': form['description'],
                                                'source': form['source'],
                                                'curr_solution': form['curr_solution'],
                                                'lim_curr_solution': form['lim_curr_solution'],
                                                'attempts': form['attempts'],
                                                'specific_goal': form['specific_goal'],
                                                'problem_id': problem_id,
                                                })


@login_required
def post_goal(request):
    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            goal = form.save(commit=False)
            init_rev = GoalRevision(title=goal.title, description=goal.description,
                                    targets=goal.targets, achievements=goal.achievements,
                                    author=request.user)
            return handle_form(goal, init_rev, request)[0]
    else:
        form = GoalForm()

    return render(request, 'goals/post.html', {'title': form['title'],
                                              'description': form['description'],
                                              'targets': form['targets'],
                                              'achievements': form['achievements'],
                                            })


@login_required
def edit_goal(request, goal_id, rev_val):

    goal = get_object_or_404(Goal, pk=goal_id)

    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            rev = form.save(commit=False)
            #right now rev is an instance of Goal class, but this line overrides its class
            rev = GoalRevision(title=rev.title, description=rev.description, targets=rev.targets,
                                    achievements=rev.achievements, author=request.user)

forum/templates/problems/edit.html
{% extends "problems/postedit.html" %}

{% load bootstrap3 %}

{% block form_action %}
    <form action="{% url 'forum:edit_problem' problem_id rev_val %}" method="post" class="form">
{% endblock %}

{% block revisions %}
    {% bootstrap_field revisions show_label=False %}
{% endblock revisions %}


{% block button %}
    {% bootstrap_icon "arrow-up" %} Save changes
{% endblock %}

forum/templates/problems/post.html
{% extends "problems/postedit.html" %}

{% load bootstrap3 %}

{% block form_action %}
    <form action="{% url 'forum:post_problem' %}" method="post" class="form">
{% endblock %}


{% block button %}
    {% bootstrap_icon "arrow-up" %} Post Problem
{% endblock %}

forum/templates/problems/postedit.html
{% extends "base.html" %}

{% load bootstrap3 %}


{% block content %}
<div class="content-row">
    <div class="left-col">

        {% block form_action %}
        {% endblock form_action %}
            {% csrf_token %}
                {% block revisions %}{% endblock revisions %}
                {% bootstrap_field goal show_label=False layout='horizontal' %}
                <ul id="found-goals">

                </ul>
                {% bootstrap_field title show_label=False %}
                {% bootstrap_field description show_label=False  %}
                {% bootstrap_field source show_label=False  %}
                {% bootstrap_field curr_solution show_label=False  %}
                {% bootstrap_field lim_curr_solution show_label=False  %}
                {% bootstrap_field attempts show_label=False  %}
                {% bootstrap_field specific_goal show_label=False  %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% block button %}
                    {% endblock button %}
                </button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock content %}

forum/templates/problems/sols.html
{# {% extends "problems/thread.html" %}

{% block bl_solutions %}


{% endblock bl_solutions %}
 #}

forum/templates/problems/thread.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}


{% block content %}
<div class="content">
    <div class="mainbar">
        <div class="title">
            <div class="title-col">
                <h3>{{ problem.title }}</h3>
            </div>
        </div>
        <div class="areas">
            <div class="areas-col">
            </div>
        </div>
        <div class="bound-row">
            <div class="bound panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="bound-goal panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      Bound Goal
                    </a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                  <ul class="list-group">
                    <li class="list-group-item"><a href="{% url 'forum:goal' problem.goal.id %}">{{ problem.goal }}</a></li>
                  </ul>
                </div>
              </div>
              <div class="bound-problems panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                  <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Bound Problems
                    </a>
                  </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <ul class="list-group">
                        {% for p in related_problems %}
                            <li class="list-group-item"><a href="{% url 'forum:thread' p.id %}">{{ p.title }}</a></li>
                        {% endfor %}
                  </ul>
                </div>
              </div>
            </div> <!-- .bound -->
        </div>
        <div class="pa">
            <div class="points">
                <span class="total-points">{{ problem.points }}</span>
                {# <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> #}
                {# <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> #}
            </div>
            <div class="author">
                <span>{{ problem.author }}</span>
            </div>
        </div>
        <div class="problem">
            <div class="problem-col">
                <h4 class="field-name">Description:</h4>
                <div class="alighned-content">
                    {{ problem.description}}
                </div>
                <h4 class="field-name">Source:</h4>
                <div class="alighned-content">
                    {{ problem.source|default:"---"}}
                </div>
                <h4 class="field-name">Current Solution:</h4>
                <div class="alighned-content">
                    {{ problem.curr_solution|default:"---"}}
                </div>
                <h4 class="field-name">Limitations of Current Solution:</h4>
                <div class="alighned-content">
                    {{ problem.lim_curr_solution|default:"---"}}
                </div>
                <h4 class="field-name">Attempts to Solve The Problem:</h4>
                <div class="alighned-content">
                    {{ problem.attempts|default:"---"}}
                </div>
                <h4 class="field-name">Specific Goal:</h4>
                <div class="alighned-content">
                    {{ problem.specific_goal|default:"---"}}
                </div>
            </div>
        </div>
        <div class="actions">
            <div class="actions-col">
                <a href="{% url 'forum:edit_problem' problem.id rev_val %}">Edit</a> Share
            </div>
        </div>
        {% if problem_questions %}
            <div class="question">
                <div class="question-col">
                    {% for question in problem_questions %}
                        {{ question.body }}
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <form action="{% url 'forum:question' problem.id 1 %}" method="post" class="form">
                {% csrf_token %}
                    {% bootstrap_field pq_body show_label=False layout='horizontal' %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                    Ask a clarifying question or suggest an improvement.
                    </button>
                {% endbuttons %}
            </form>
        {% endif %}

        {% if solutions.count > 0 %}
            <div class="solutions-count"><h3>{{ solutions.count }} Solution{{ solutions.count|pluralize }}</h3></div>
            <div class="solutions">
                <div class="solutions-col">
                        {% for solution in solutions %}
                            <div class="pa">
                                <div class="points">
                                    <p>{{ solution.points }}</p>
                                </div>
                                <div class="author">
                                    <p>{{ solution.author }}</p>
                                </div>
                            </div>
                            <p class="sol-body">{{ solution.body }}</p>
                            <div class="actions">
                                <div class="actions-col">
                                    <a href="{% url 'forum:edit_solution' solution.id rev_val %}">Edit</a> Share
                                </div>
                            </div>
                        {% endfor %}
                    </div>
            </div>
        {% endif %}


        <form action="{% url 'forum:thread' problem.id %}" method="post" class="form">
            {% csrf_token %}
                {% bootstrap_field body show_label=False layout='horizontal' %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                Post Solution
                </button>
            {% endbuttons %}
        </form>


    </div> <!-- .mainbar -->
    <div class="sidebar">
        <div class="bound-side">
            <div class="bound-goal-side">
                <h4>Bound Goal</h4>
                <a href="{% url 'forum:goal' problem.goal.id %}">{{ problem.goal }}</a>
            </div>
            <hr>
            <div class="bound-problems-side">
                <h4>Bound Problems</h4>
                {% for p in related_problems %}
                    <a href="{% url 'forum:thread' p.id %}">{{ p.title }}</a>
                {% endfor %}

            </div>
        </div>
    </div> <!-- .sidebar -->
</div>

{% endblock content %}

<!-- http://www.bootply.com/7q3q5hRQRZ -->